CREATE TABLE TIPO_USUARIO(
    ID_TIPO_USUARIO NUMBER(1),
    ESTADO VARCHAR(1) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TIPO_USUARIO)
);

CREATE TABLE USUARIOS(
    ID_USUARIO NUMBER(3),
    NOMUSUARIO VARCHAR(25) NOT NULL UNIQUE,
    PASSUSUARIO VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    ESTADO VARCHAR(1) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ALUMNO(
    MATRICULA CHAR(8),
    NOMBRE VARCHAR(30) NOT NULL,
    APATERNO VARCHAR(30) NOT NULL,
    AMATERNO VARCHAR(30),
    TELEFONO CHAR(10) NOT NULL UNIQUE,
    GRUPO CHAR(1) NOT NULL,
    SEMESTRE NUMBER(2) NOT NULL,
    CARRERA VARCHAR(20) NOT NULL,
    FOTO VARBINARY(MAX) NOT NULL,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE LOCALIZACION(
    ID_LOC NUMBER(3),
    MATRICULA CHAR(9),
    LOCALIDAD VARCHAR(25) NOT NULL,
    CIUDAD_ORIGEN VARCHAR(25) NOT NULL,
    COLONIA VARCHAR(25) NOT NULL,
    CALLE VARCHAR(25) NOT NULL,
    CODIGO_POSTAL VARCHAR(5) NOT NULL,
    PRIMARY KEY (MATRICULA, ID_LOC), 
    FOREIGN KEY (MATRICULA) REFERENCES ALUMNO(MATRICULA)
);

CREATE TABLE MIS_DOCUMENTOS(
    MATRICULA CHAR(9),
    ID_DOCS NUMBER(1),
    RFC VARBINARY(MAX) NOT NULL,
    ACTA_NACIMIENTO VARBINARY(MAX) NOT NULL,
    CURP VARBINARY(MAX) NOT NULL,
    PRIMARY KEY (MATRICULA, ID_DOCS),
    FOREIGN KEY (MATRICULA) REFERENCES ALUMNO(MATRICULA)
);