CREATE TABLE TIPO_USUARIO(
    ID_TIPO_USUARIO INT  PRIMARY KEY,
    ESTADO NVARCHAR(1) NOT NULL,
    DESCRIPCION NVARCHAR(50) NOT NULL,
);

CREATE TABLE USUARIOS(
    ID_USUARIO INT,
    NOMUSUARIO NVARCHAR(25) NOT NULL UNIQUE,
    PASSUSUARIO NVARCHAR(80) NOT NULL,
    EMAIL NVARCHAR(128) NOT NULL,
    ESTADO NVARCHAR(1) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ALUMNO(
    MATRICULA CHAR(8),
    NOMBRE NVARCHAR(30) NOT NULL,
    APATERNO NVARCHAR(30) NOT NULL,
    AMATERNO NVARCHAR(30),
    TELEFONO CHAR(10) NOT NULL UNIQUE,
    GRUPO CHAR(1) NOT NULL,
    SEMESTRE INT NOT NULL,
    CARRERA NVARCHAR(20) NOT NULL,
    FOTO VARBINARY(MAX) NOT NULL,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE LOCALIZACION(
    ID_LOC INT,
    MATRICULA CHAR(8),
    LOCALIDAD NVARCHAR(25) NOT NULL,
    CIUDAD_ORIGEN NVARCHAR(25) NOT NULL,
    COLONIA NVARCHAR(25) NOT NULL,
    CALLE NVARCHAR(25) NOT NULL,
    CODIGO_POSTAL CHAR(5) NOT NULL,
    PRIMARY KEY (MATRICULA, ID_LOC), 
    FOREIGN KEY (MATRICULA) REFERENCES ALUMNO(MATRICULA)
);

CREATE TABLE MIS_DOCUMENTOS(
    MATRICULA CHAR(8),
    ID_DOCS INT,
    RFC VARBINARY(MAX) NOT NULL,
    ACTA_NACIMIENTO VARBINARY(MAX) NOT NULL,
    CURP VARBINARY(MAX) NOT NULL,
    PRIMARY KEY (MATRICULA, ID_DOCS),
    FOREIGN KEY (MATRICULA) REFERENCES ALUMNO(MATRICULA)
);